### ISSUE TITLE
The Bash logger script adds extra single quotes around fields and breaks the log collector.

### ISSUE THREAD

**Issue by bpmcd** [phdata/pulse#17]
Stack trace: 

> Error posting documents to solr
org.apache.solr.common.SolrException: Could not find collection : 'kafka_kudu_streaming'_latest
	at org.apache.solr.common.cloud.ClusterState.getCollection(ClusterState.java:162)
	at org.apache.solr.client.solrj.impl.CloudSolrServer.directUpdate(CloudSolrServer.java:324)
	at org.apache.solr.client.solrj.impl.CloudSolrServer.request(CloudSolrServer.java:563)
	at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:124)
	at io.phdata.pulse.common.SolrService.insertDocuments(SolrService.scala:176)

Can be fixed by updating the logger.sh script to not quote every property, or by sanitizing the params in the log-collector POST handler...

**Comment by bpmcd** [comment]
HA!  I just realized you already fixed this.....
