### ISSUE TITLE
Empty SMTP password config results in alert engine crash

### ISSUE THREAD

**Issue by bpmcd** [phdata/pulse#50]
2018-08-27 14:40:20,134 INFO io.phdata.pulse.alertengine.notification.MailNotificationService: starting notification for profile mailProfile1
2018-08-27 14:40:20,185 INFO io.phdata.pulse.alertengine.notification.MailNotificationService: sending alert
2018-08-27 14:40:20,186 INFO io.phdata.pulse.alertengine.notification.Mailer: authenticating with password
2018-08-27 14:40:20,320 ERROR io.phdata.pulse.alertengine.AlertEngineMain$: caught exception in Collection Roller task
javax.mail.AuthenticationFailedException: null
	at javax.mail.Service.connect(Service.java:306)
	at javax.mail.Service.connect(Service.java:156)
	at javax.mail.Service.connect(Service.java:105)
	at javax.mail.Transport.send0(Transport.java:168)
	at javax.mail.Transport.send(Transport.java:98)
	at io.phdata.pulse.alertengine.notification.Mailer.sendMail(Mailer.scala:60)
	at io.phdata.pulse.alertengine.notification.MailNotificationService$$anonfun$notify$1.apply(MailNotificationService.scala:35)
	at io.phdata.pulse.alertengine.notification.MailNotificationService$$anonfun$notify$1.apply(MailNotificationService.scala:31)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at io.phdata.pulse.alertengine.notification.MailNotificationService.notify(MailNotificationService.scala:31)
	at io.phdata.pulse.alertengine.AlertEngineImpl$$anonfun$sendAlert$1.apply(AlertEngineImpl.scala:139)
	at io.phdata.pulse.alertengine.AlertEngineImpl$$anonfun$sendAlert$1.apply(AlertEngineImpl.scala:138)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at io.phdata.pulse.alertengine.AlertEngineImpl.sendAlert(AlertEngineImpl.scala:138)
	at io.phdata.pulse.alertengine.AlertEngineImpl$$anonfun$notify$1.apply(AlertEngineImpl.scala:112)
	at io.phdata.pulse.alertengine.AlertEngineImpl$$anonfun$notify$1.apply(AlertEngineImpl.scala:110)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at io.phdata.pulse.alertengine.AlertEngineImpl.notify(AlertEngineImpl.scala:110)
	at io.phdata.pulse.alertengine.AlertEngineImpl.run(AlertEngineImpl.scala:45)
	at io.phdata.pulse.alertengine.AlertEngineMain$AlertEngineTask.run(AlertEngineMain.scala:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-08-27 14:40:20,321 WARN io.phdata.pulse.alertengine.AlertEngineMain$: Caught exit signal, trying to cleanup tasks

**Comment by bpmcd** [comment]
When the SMTP_PASSWORD environment variable is read (in AlertEngineCliParser) the value that comes through is the empty string.  This appears to be the default value as specified in the service.sdl (line: 195).

**Comment by bpmcd** [comment]
Fixed.
